### ISSUE TITLE
[Remoto] Front-end Developer na ARK Ecosystem

### ISSUE THREAD

**Issue by luciorubeens** [frontendbr/vagas#2781]
## Nossa empresa

A Ark Ecosystem é uma empresa com sede na França, que visa criar um ecossistema de blockchains conectadas fornecendo ferramentas open-source e fáceis de utilizar para publicar sua própria blockchain.

Website: [ark.io](https://ark.io)
Github: [/ArkEcosystem](https://github.com/ArkEcosystem)

### Diferenciais

- Horário flexível
- Salário competitivo
- Trabalhar com novas tecnologias
- Contribuir com projetos open source

## Descrição da vaga

Estamos expandindo nossos projetos e procuramos por desenvolvedores front-end.

Você será responsável implementar novas funcionalidades e manter alguns de nossos projetos, como:

- [Desktop Wallet](https://github.com/arkecosystem/desktop-wallet)
- [Explorer](https://github.com/arkecosystem/explorer)
- [Mobile Wallet](https://github.com/arkecosystem/mobile-wallet)

## Local

Remoto

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com Node.js
- 2 anos de experiência com alguma biblioteca/framework front-end (Vue.js, React, Angular)
- Conhecimentos em Git
- Inglês intermediário

**Desejáveis:**
- Vue.js
- TypeScript
- Electron.js
- Experiência com ferramentas de testes como Jest

**Diferenciais:**
- Conhecimentos básicos em criptografia
- Experiência com Laravel
- Experiência com Tailwind CSS

## Contratação

- PJ ou PF
- Salário baseado em Euro com pagamento em Bitcoin, ARK ou combinação das duas.

## Como se candidatar

Por favor envie um email para jobs@ark.io com seu CV anexado (**em inglês**) - enviar no assunto: Front-End Developer

## Labels

- Remoto
- Pleno
- Exterior

[Leia a descrição completa da vaga em inglês](https://blog.ark.io/wanted-front-end-developer-cf7b081cb28).

**Comment by luciorubeens** [comment]
💡 Caso você não se adeque aos requisitos da vaga, também temos os programas de recompensa mensais de **desenvolvimento** e **segurança**. No programa de desenvolvimento, estão inclusos correção de bugs, refatoração, implementação de novas funcionalidades, melhorias de perfomance, com recompensas a partir de $20 até $200 por *pull request* aprovado! Já no programa de segurança, as recompensas vão de $100 até $10,000.

[Leia mais sobre e acompanhe os valores pagos](https://ark.io/bounties).

**Comment by italomlp** [comment]
Esse inglês intermediário inclui conversação oral também? Pergunto pois consigo me comunicar relativamente bem em inglês via leitura e escrita, mas minha conversação oral ainda está em WIP.

**Comment by luciorubeens** [comment]
@italomlp Apenas leitura e escrita é suficiente!

**Comment by humbertoromanojr** [comment]
olá tudo bem Lucio, me interessei muito em entrar "**programas de recompensa mensais de desenvolvimento**".

**Obrigatórios:**
2 anos de experiência com Node.js
2 anos de experiência com alguma biblioteca/framework front-end (React)
Conhecimentos em Git
Inglês intermediário

**Desejáveis:**
TypeScript ---> meu foco atualmente
Electron.js ---> fiz alguns CRUDs para aprender 
Experiência com ferramentas de testes como Jest ---> pouco do meu curso na Rocketseat

**Diferenciais:**
Experiência com Laravel ---> eu migrei de PHP para JS e estava trabalhando com laravel
Experiência com Tailwind CSS ---> fui dar uma olhada, e gostei do Framework

Lucio veja o meu Github e me fale se tenho condições para trabalhar com vocês 
tenha uma ótima semana

**Comment by luciorubeens** [comment]
@humbertoromanojr Não participo do processo de seleção, mas você pode enviar seu currículo como instruído na descrição.

Para participar dos programas de desenvolvimento não é necessário nenhum cadastro, basta enviar seu pull request para algum de nossos repositórios.

**Comment by humbertoromanojr** [comment]
Muito Obrigado por me responder, irei providencias o mais rápido possível o
meu CV em inglês


Atenciosamente,

Humberto Junior




Em sex., 10 de jan. de 2020 às 07:01, Lúcio Rubens <notifications@github.com>
escreveu:

**Comment by humbertoromanojr** [comment]
Lucio boa tarde, por favor você que entende mais as coisas e negócios,
gostaria de uma opinião sincera, porque tenho medo de entrar em furada e
piorar a minha situação, agora estou desempregado mais eu não devo nada a
ninguém, me chegou um email da Corea do sul com a seguinte proposta, devo
ou não devo aceitar?

========================================= no email veio este texto
My name is Jin and I am running software and electronic development team in
South Korea. I have 10 software engineers and 7 hardware engineers.

I want to expand our business to US.

Nowadays, I can find many software development jobs in upwork.com but
unfortunately we can’t create upwork developer account in South Korea
because upwork.com doesn’t accept asian accounts.

So I want to make the business partnership with you.

Here are the short business plan.

Your role : you will create your upwork account with your information and
get the jobs from upwork.com
My role : I will let my team to complete the jobs clearly.
Profit : You will get 10 or 15 percentage of total cost.

My team member can apply to the jobs via your account and you can do only
interview to get the jobs. So I think it will take 5 hours per week for
you.

You are great software engineer and my team has a capability to complete
the jobs. So I think we can cooperate together.

I will wait your response.

Best.
============================================================================
Desculpe o incomodo Lucio, mais estou precisando ter renda para quitar as
minhas dívidas básicas



Atenciosamente,

Humberto Junior




Em sáb., 11 de jan. de 2020 às 11:03, HUMBERTO ROMANO <astronomi@gmail.com>
escreveu:

**Comment by renangarciasoz** [comment]
@luciorubeens , enviei o resumo e também te adicionei no LinkedIn, let's code? 🔥

**Comment by humbertoromanojr** [comment]
Renan para onde que enviou este Resumo?

eu não consegui encontrar


Atenciosamente,

Humberto Junior




Em qua., 15 de jan. de 2020 às 21:24, Renan Garcia <notifications@github.com>
escreveu:
