### ISSUE TITLE
[São paulo ou 100% Remoto] Front-End Developer - React  na Enki Labs

### ISSUE THREAD

**Issue by Odare** [frontendbr/vagas#3363]
## Nossa empresa

Aqui na Enki Labs desenvolvemos sistemas para comunicação de atendimento. 
Se você procura um lugar onde você quer ser ouvido, tem um pessoal legal, e uma equipe parceira. Vem falar com a gente.

## Descrição da vaga

Arquitetar e Desenvolver a parte front-end da nossa plataforma de serviço SaaS, juntamente com equipe multidisciplinar.

## Local

Remoto, ou na Al Santos em São Paulo

## Requisitos

**Obrigatórios:**
- HTML/CSS (Ou expansões como SCSS)
- Javascript
- Typescript
- React
- Redux (ou equivalente para sagas)
- SPA (Single Page Application)
- Automação de testes
- Builders (WebPack)
- Comunicação com APIs (REST/Json)
- Orientação Objetos + SOLID
- Versionamento de código (Usamos Git)
- Inglês (Código em inglês)

## Benefícios

- Férias remuneradas

## Contratação

PJ a partir de R$5.000,00 a R$10.000,00(de acordo com a sua experiência)

## Como se candidatar

Por favor envie um email para vagas[arroba]encontact.com.br com seu CV anexado - enviar no assunto: Front-End Developer - React

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: atendimento[arroba]encontact.com.br

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by jorginhodev** [comment]
O e-mail está correto?

**Comment by HenriqueACF** [comment]
aceita júnior?Em 28 de jul de 2020 11:07 AM, Odare <notifications@github.com> escreveu:

Nossa empresa

Aqui na Enki Labs desenvolvemos sistemas para comunicação de atendimento.

Se você procura um lugar onde você quer ser ouvido, tem um pessoal legal, e uma equipe parceira. Vem falar com a gente.

Descrição da vaga

Arquitetar e Desenvolver a parte front-end da nossa plataforma de serviço SaaS, juntamente com equipe multidisciplinar.

Local

Remoto, ou na Al Santos em São Paulo

Requisitos

Obrigatórios:

HTML/CSS (Ou expansões como SCSS)JavascriptTypescriptReactRedux (ou equivalente para sagas)SPA (Single Page Application)Automação de testesBuilders (WebPack)Comunicação com APIs (REST/Json)Orientação Objetos + SOLIDVersionamento de código (Usamos Git)Inglês (Código em inglês)

Benefícios

Férias remuneradas

Contratação

PJ a partir de R$5.000,00 a R$10.000,00(de acordo com a sua experiência)

Como se candidatar

Por favor envie um email para vagasencontact.com.br com seu CV anexado - enviar no assunto: Front-End Developer - React

Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.

E-mail para contato em caso de não haver resposta: atendimentoencontact.com.br

Labels

Alocação

Remoto

Regime

PJ

Nível

PlenoSênior

**Comment by Odare** [comment]
> O e-mail está correto?

Obrigado, o git comeu minha tag

**Comment by Odare** [comment]
> aceita júnior?Em 28 de jul de 2020 11:07 AM, Odare <notifications@github.com> escreveu: Nossa empresa Aqui na Enki Labs desenvolvemos sistemas para comunicação de atendimento. Se você procura um lugar onde você quer ser ouvido, tem um pessoal legal, e uma equipe parceira. Vem falar com a gente. Descrição da vaga Arquitetar e Desenvolver a parte front-end da nossa plataforma de serviço SaaS, juntamente com equipe multidisciplinar. Local Remoto, ou na Al Santos em São Paulo Requisitos Obrigatórios: HTML/CSS (Ou expansões como SCSS)JavascriptTypescriptReactRedux (ou equivalente para sagas)SPA (Single Page Application)Automação de testesBuilders (WebPack)Comunicação com APIs (REST/Json)Orientação Objetos + SOLIDVersionamento de código (Usamos Git)Inglês (Código em inglês) Benefícios Férias remuneradas Contratação PJ a partir de R$5.000,00 a R$10.000,00(de acordo com a sua experiência) Como se candidatar Por favor envie um email para vagasencontact.com.br com seu CV anexado - enviar no assunto: Front-End Developer - React Tempo médio de feedbacks Costumamos enviar feedbacks em até 5 dias após cada processo. E-mail para contato em caso de não haver resposta: atendimentoencontact.com.br Labels Alocação Remoto Regime PJ Nível PlenoSênior —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

Olá Henrique!
No momento estamos precisando de alguém com mais experiência. Nossa equipe não domina o React.

**Comment by HenriqueACF** [comment]
agradeço o feedbackEm 28 de jul de 2020 2:54 PM, Odare <notifications@github.com> escreveu:



aceita júnior?Em 28 de jul de 2020 11:07 AM, Odare notifications@github.com escreveu: Nossa empresa Aqui na Enki Labs desenvolvemos sistemas para comunicação de atendimento. Se você procura um lugar onde você quer ser ouvido, tem um pessoal legal, e uma equipe parceira. Vem falar com a gente. Descrição da vaga Arquitetar e Desenvolver a parte front-end da nossa plataforma de serviço SaaS, juntamente com equipe multidisciplinar. Local Remoto, ou na Al Santos em São Paulo Requisitos Obrigatórios: HTML/CSS (Ou expansões como SCSS)JavascriptTypescriptReactRedux (ou equivalente para sagas)SPA (Single Page Application)Automação de testesBuilders (WebPack)Comunicação com APIs (REST/Json)Orientação Objetos + SOLIDVersionamento de código (Usamos Git)Inglês (Código em inglês) Benefícios Férias remuneradas Contratação PJ a partir de R$5.000,00 a R$10.000,00(de acordo com a sua experiência) Como se candidatar Por favor envie um email para vagasencontact.com.br com seu CV anexado - enviar no assunto: Front-End Developer - React Tempo médio de feedbacks Costumamos enviar feedbacks em até 5 dias após cada processo. E-mail para contato em caso de não haver resposta: atendimentoencontact.com.br Labels Alocação Remoto Regime PJ Nível PlenoSênior —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.



Olá Henrique!

No momento estamos precisando de alguém com mais experiência. Nossa equipe não domina o React.

**Comment by danyelhenrique** [comment]
Desculpe mais o email ``vagasencontact.com.br`` para o envio do curriculo  esta corrento ?

**Comment by Odare** [comment]
> Desculpe mais o email `vagasencontact.com.br` para o envio do curriculo esta corrento ?

Olá Danyelhenrique , o email correto é vagas[arroba]encontact.com.br
