### ISSUE TITLE
[São Paulo-Butantã/Pinheiros] Front-End Developer Sênior na Voxel Digital

### ISSUE THREAD

**Issue by evandronasc** [frontendbr/vagas#613]
## Descrição da vaga
A Voxel Digital está ampliando a equipe de desenvolvimento e marketing digital. Os projetos estão muito focados em desenvolvimento de produtos e aplicações web (websites, webapps e aplicações touchscreen).

[ IMPORTANTE ] O nível técnico desta vaga é SÊNIOR com mais de 5 anos de experiência na área. 
Para este momento não temos vagas para perfis júnior e pleno. Gostaríamos de receber candidatos somente com perfil SÊNIOR.

## Local
Somente Alocado em São Paulo - Butantã

## Benefícios
• Restaurante no local; 
• Voxel Garden - Área de Descompressão; 
• Assistência Médica; 
• Seguro de Vida; 
• Vale transporte. 

## Requisitos

**Obrigatórios:**
- Nível técnico: SÊNIOR
- Mínimo de 5 anos de experiência com desenvolvimento web
- HTML avançado; 
- CSS avançado; 
- SEO avançado; 
- SASS avançado;
- WORDPRESS avançado;
- BOOTSTRAP avançado;
- JAVASCRIPT intermediário/avançado. 

**Desejáveis:**
- Banco de dados (SQL, MySQL), 
- API (RESTFull, Webservice). 
- PHP
- Framework MV*

## Contratação
PJ OU CLT

## Remuneração
Faixa salarial de R$6,5k a R$10k

## Nossa empresa
A Voxel Digital é líder em tecnologias para distribuição de conteúdos digitais no Brasil. Temos soluções para EAD, Digital Signage e Transmissão ao Vivo ou Sob Demanda. Atendemos clientes como Bradesco, Net, Estácio, Consigaz, Toyota, Endeavor e muito mais.

## Como se candidatar
Por favor acesse https://voxeldigital.gupy.io/candidates/vacancy/59caaf7f0d086a7f943d8b5e/ e faça o cadastro. 

Ps. Não esqueça de mencionar que viu a vaga aqui no frontendbr

**Comment by paulo70** [comment]
@evandronasc Boa tarde, 

Apenas um comentário sem causar discussão, ok.
Fica um pouco desestimulante preencher um cadastro de meia hora pra uma vaga de tecnologia, temos Linkedin e Github para agiizar esse processo, a empresa tendo interesse com essas informações que no caso são bem completas o filtro fica sendo melhor pra vocês.

Veja o nosso caso como desenvolvedores, lemos a descrição da vaga e nos baseamos nessas informações pra saber se temos interesse ou não.

obs: Essa é apenas a forma que encaro essa situação, a empresa é livre pra fazer da forma que achar melhor.
Um abraço.

**Comment by evandronasc** [comment]
@paulo70 
Boa noite Paulo, tudo bem?
Obrigado pelo seu comentário. Entendo seu ponto de vista e acredito que você até tenha razão quando se trata da perspectiva do candidato. É mais prático enviar um currículo, github, linkedin e aguardar o contato da empresa.

A questão é que também buscamos evitar que o candidato perca tempo, as vezes 2 ou 3 horas, deslocando-se até a empresa, pra chegar aqui e perceber que não é aquilo que esperava ou então receber uma resposta negativa que poderia muito bem ter sido evitada se isso fosse identificado previamente, através de um simples avaliação.

Acreditamos que preencher os dados também nos ajuda a entender se o candidato está realmente interessado em conhecer a empresa e a proposta de valor que ela oferece ou se está apenas enviando currículos no modo spam.

Atenciosamente,

**Comment by DeniseCavalcante** [comment]
Boa noite sr.Paulo,

Obrigada pelo aviso. Ativei algum botão  no git hub que está enviando spam,
ainda estou conhecendo a plataforma, sou front júnior nem poderia me
candidatar a essa vaga.

Mais uma vez.

Muito obrigada

Att

Denise Cavalcante




Em 19 de out de 2017 20:27, "Evandro Nascimento" <notifications@github.com>
escreveu:

@paulo70 <https://github.com/paulo70>
Boa noite Paulo, tudo bem?
Obrigado pelo seu comentário. Entendo seu ponto de vista e acredito que
você até tenha razão quando se trata da perspectiva do candidato. É mais
prático enviar um currículo, github, linkedin e aguardar o contato da
empresa.

A questão é que também buscamos evitar que o candidato perca tempo, as
vezes 2 ou 3 horas, deslocando-se até a empresa, pra chegar aqui e perceber
que não é aquilo que esperava ou então receber uma resposta negativa que
poderia muito bem ter sido evitada se isso fosse identificado previamente,
através de um simples avaliação.

Acreditamos que preencher os dados também nos ajuda a entender se o
candidato está realmente interessado em conhecer a empresa e a proposta de
valor que ela oferece ou se está apenas enviando currículos no modo spam.

Atenciosamente,

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/frontendbr/vagas/issues/613#issuecomment-338055536>,
or mute
the thread

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
