### ISSUE TITLE
[FULLY REMOTE] Fullstack Engineer (React+Java) at Jobsity

### ISSUE THREAD

**Issue by AngelaBarboza** [frontendbr/vagas#8076]
## About [Jobsity](https://www.jobsity.com/)💡
We’ve been around for about 10 years. We are a NY based staffing company that works with lots of different clients in the US, Canada and Europe.
Most of our developers, data engineers, and Quality Assurance engineers are located in Latin America, although we have a presence in more than 15 countries.
We have connected more than 400 people with international employment. We focus more on quality and long-term partnerships, between Jobsity, our candidates (you), and our clients. In fact, we only work with the top 3% of talents in LATAM.
As a member of the Jobsity Recruitment team, we are going to work to find you the right position depending on what is important to you.

## Requirements✔

🔥 Conversational English level. 
🔥 Strong full-stack development capabilities (Frontend oriented), and ability to build APIs seamlessly and design beautiful frontend interfaces.
🔥 5+ years of experience as a FullStack Engineer working with:
- In Frontend: React and Typescript,
- In Backend: Java or Kotlin (at least 2 years of recent experience).
- SQL dbs like Postgres.

🔥 Proper understanding of SOLID principles.
🔥 Familiarity with microservices architecture conceptually.
🔥 Some high-level knowledge of Docker and containerization.
🔥 Good experience with data modeling.
🔥 Experience in feature design and UX planning.

## Modality
👨‍💻 Fully remote
PS: position available only for engineers located in LATAM 🗺

## Perks that Jobsity offers!💎

🔹15 business days of paid vacation yearly.
🔹3 extra off days per year.
🔹Paid local holidays.
🔹Learning budget.
🔹Financing program for equipment and home office supplies.
🔹Betterfly app (wellness).
🔹Bonuses for referrals and more!

## Type of contract📜

This is a full-time position as contractor🕘
....with USD payment 💰
....long-term relationship 🤝
...within an international team 👩‍💻 👨‍💻
...and working on international client projects! 🌎

## How to apply🤔

- Send an email to [angela.barboza@jobsity.com](mailto:angela.barboza@jobsity.com) with your CV/LinkedIn attached - Send in the subject: Fullstack Engineer (React+Java) - GitHub📧

**Comment by AngelaBarboza** [comment]
The search is paused!⛔ Thank you for your messages! 😉

**Comment by kabeer95** [comment]
With great pleasure, I would like to introduce you to Jobsity's outstanding opportunity for a FullStack Engineer (Frontend Oriented). With more than a decade of experience bridging the gap between elite Latin American talent and global clients, I'm  dedicated to building strong, long-lasting relationships. Using SOLID principles and microservices architecture, you and your team will collaborate on innovative projects utilizing React, TypeScript, Java/Kotlin, and Postgres. Please apply so that you can develop with us if you're passionate about building slick APIs, making user-friendly interfaces, and collaborating with a vibrant, varied team.
